### ISSUE TITLE
>>#selectAny: and difference of VOMemoryRepository and VOMongoRepository

### ISSUE THREAD

**Issue by zecke** [pharo-nosql/voyage#48]
For a unit test I have inserted one record and I know there is only one and would like to retrieve it. My unit test is using VOMemoryRepository and I do:

```
res := repository selectOne: BlaClass where: [:each | true].
self assert: res...
```

If I do the same with the VOMongoRepository then I get

```
Can't canonicalize query: BadValue: unknown top level operator: $query
```

inside the $err string. It might be the easiest to add a selectAny to VOMongoRepository/VOMemoryRepository or can you think of something else?

**Comment by noha** [comment]
When using a block in a query it constructs a MongoQuery which is supposed to be the value of the block. true is not a mongo query. But using #selectAll would do the kob ;)

**Comment by zecke** [comment]
True. If I know there is only one I can do (selectAll: Class) first but somehow this still feels wasteful (fetch all results and throw away the rest). I wouldn't want to add such code. :)

**Comment by noha** [comment]
If there is more than one the specification of "true" does not make much sense either ;) If you insist doing that you can use: selectOne: [ :query | query where: 'true' ]. I cannot think of another possibility yet. But again you get a MongoQuery object that helps making queries easier. It is one of this basic implementation showing how cool it could be but the are that kind of limited you have to use the dictionary approach pretty soon

**Comment by noha** [comment]
Is there still things to discus/change?

**Comment by zecke** [comment]
Well, the question is if Mongo/NoSQL/Memory should have the _same_ protocol (and similar behavior) or not. I used to substitute VOMongoRepository for VOMemoryRepository in my unit tests but I know I can create facades for that too.

**Comment by noha** [comment]
The protocol question is two-fold. There is a superclass called VORepository. The protocol of VORepository must be implemented in the specific subclasses and it needs to behave the same. Otherwise you cannot swap out one implementation and swap in another one because you would need to adjust business logic. But the specific subclasses have additional protocols to configure and use specific behaviour of the database. The biggest task we need to solve is how you can have a generic way of setting things that trigger the right behaviour in the specific implementation. This way we can have a generic object serializer and ways to make it behave more efficient on a specific database

**Comment by noha** [comment]
But I have a look into it if either of the implementations need to change

**Comment by noha** [comment]
It seems this is a misunderstanding. Using blocks in queries does not mean that it should support all smalltalk expressions. It is rather that the restricted set of database operations can look like smalltalk
