### ISSUE TITLE
How do VORepository>>commit: and VORepository>>root:commit: differ from VORepository>>save:?

### ISSUE THREAD

**Issue by dalehenrich** [pharo-nosql/voyage#49]
There are no tests using these two methods, so I'm not sure what the semantics are supposed to be ... For GemStone I do a db commit during VORepository>>save:, so perhaps  VORepository>>commit: and VORepository>>root:commit: aren't really necessary? Or perhaps I'm missing something else?

**Comment by estebanlm** [comment]
Hi @dalehenrich, 

Currently they do not have much use, but that can change. The original idea was to create a kind of "unit of work" with it...  the idea was that this:

```Smalltalk
repository commit: [ 
    a save.
    b save ]
```

was going to happen inside a transaction (and rollback if things fail). I used it in one backend I made (with GLORP) for a project... root:commit: was the same idea but a workaround when I need to know the root of to made the commit of a graph. 

But this is old history and those methods do not have practical use today. We can decide to give them new use (because gemstone allows transactions, and also unqlite... but not mongodb), or we can just drop them...

**Comment by dalehenrich** [comment]
Okay the unit of work idea is interesting ... and grouping a bunch of saves can have some utility I would imagine ... and yes in mongo there is not much to see from that perspective ..

**Comment by estebanlm** [comment]
so we close this?

**Comment by dalehenrich** [comment]
yes ... Thanks!
