### ISSUE TITLE
session-based object cache?

### ISSUE THREAD

**Issue by dalehenrich** [pharo-nosql/voyage#52]
I think this is somewhat related to #49...

When you have a repository-based cache it means that you cannot manage separate local object copies that may represent object state for a particular view of the repository. 

If the cache were managed on a session by session basis, then object lookup and sharing would be guaranteed to be consistent with the db view associated with the session ...

besides, sharing common objects between two sessions can get quite confusing ...

Don't know if this has come up before or not.

**Comment by dalehenrich** [comment]
I see that in your unqlite work you are using a different caching scheme altogether so the resolver-based cache wrapping the "session pool" is a Mongo thing not a Voyage thing ... so never mind :)

**Comment by estebanlm** [comment]
Hi @dalehenrich, 
In fact, caches in voyage are used just to grant object identity... in mongo is centralised because object id are unique in database, not just in collection (this is a consequence of the fact that to this day, mongo cannot give you the id of the inserted object... as it should, IMO, so we calculate them before inserting... an approach that of course has problems, but well, this is like that).
In UnQLite I choose other approach (keep one cache per collection) because unqlite *does* gives you an id back... but this is collection related so I needed to choose another approach to keep objects... I could have done it different, but this was the easier/faster approach...  in fact I was playing with the idea of also keep collection-based caches in mongo, as I think big weak collections does not behave as fast as smaller ones, then this would be a way to optimise... but anyway, I didn't do anything about, yet :)

**Comment by dalehenrich** [comment]
With only the MongodDB implementation to look at it was hard to differentiate between necessity and desire:) ... Speaking of caches ... it seems to me that there are some inherent difficulties in keeping the caches coherent when there are more than one image/repository interacting with the db...

For example in [this test](https://github.com/dalehenrich/voyage/blob/uncle/mc/Voyage-Tugrik-Tests.package/VORepositoryTest.extension/instance/testCrossImageRootUpdates.st), I found it relatively easy to introduce inconsistencies in the cache when another session is makes changes to an already cached object ... 

It seems that this kind of cache inconsistency is a *feature of NOSQL* so I'm not sure that it is a real issue as long as you refresh each object you intend to change --- I wrote the test because a) I wanted to verify that Tugrik conformed with Mongo and b) I want to solve the issue for Tugrik --- and I think that by using session-based caches, synced to a GemStone view that I can provide consistent caches

**Comment by noha** [comment]
The feature ist called "eventually consistent". Where we could improve is the handling of version in mongo. The cache only ensures identity. Every time a query is issued there is a real query to the database. The version information in the json is taken to decide if the object needs to be materialized again. To make that more consistent there should be a form of upgrade that stores the object in the database only if it has still the same version number. The pattern to use for mongo is called "update if current".

**Comment by noha** [comment]
Is this resolved? I would want to know what @dalehenrich means when using "session" related to voyage. Apart from that?
