### ISSUE TITLE
Pin mongotalk to specific version instead of loading master

### ISSUE THREAD

**Issue by noha** [pharo-nosql/voyage#63]
As we all know referring to a symbolic version does not work, be it stable or development. In git parlance this would be the master brach which is the default if only specifying the repository. I think it is unavoidable to have deliberate version updates of mongotalk and all dependent projects.
So I propose to release a new version of mongotalk and pin the voyage configuration to that version until there is an update of mongotalk we want to integrate. Any thoughts?

**Comment by dalehenrich** [comment]
@noha, I think that makes sense ... you might use [tag pattern matching](https://github.com/dalehenrich/metacello-work/issues/277#issuecomment-58970840) to allow for bugfixes without having to re-release the configuration and if the master branch has progressed to far, the later tags can be on a bugfix branch ...

**Comment by noha** [comment]
Thanks for the tip. I tried to do but I don't have access rights to the mongotalk repository. @tinchodias Can we release mongotalk as 1.10.0? I tried pinning voyage to the old 1.9.5 version but there are classes missing. So if there are no objections it would be best to release mongotalk 1.10.0 and pin voyage to it

**Comment by noha** [comment]
So, it is done. Pull request #64 includes the change

**Comment by noha** [comment]
@dalehenrich I tried your advize but it does not work. Using a ? in a version number let pharo3 and pharo4 on travis fail. So I guess the metacello in there is too old. I'm not sure if we have to wait until we retire the old versions or if there is something better

**Comment by noha** [comment]
We decided to use a tag scheme to support the same thing. 1.10.0 is a version tag fixed at its commit. There is a tag 1.10 which is moves up in all 1.10.* versions. So voyage's baseline pins mongotalk to 1.10 which includes all the bug fixes in 1.10.*

**Comment by dalehenrich** [comment]
hmmm. sounds like a Metacello or SmalltalkCI bug ...The metacello tests pass on pharo-3.0 and pharo-4.0 but then they also load the latest version of Metacello .. I think I'll submit a bug to SmalltalkCI, since I think it should be an option to update Metacallo to the latest version when running travis tests ... since there will always be the possibility that a particular Metacello bugfixis needed to be able load a project ...

**Comment by noha** [comment]
I think all images should stay plain vanilla because the projects should be loadable in a fresh image without preparation.

**Comment by dalehenrich** [comment]
I agree 100%, but when a project _requires_ the latest version of Metacello, then you need a way to force Metacello to be updated ... if you feel that this shouldn't be an *option*, then please comment on the issue hpi-swa/smalltalkCI#197 and take part in the discussion there ...

In your particular case you chose a solution that does not require the latest version of Metacello and that _is_ and always should be your choice, but projects that are choosing to go Metadataless should not be forced into [ugly hacks](https://github.com/krono/MaterialDesignLite/blob/30945cd1af67f9f1806832ded8d3d566c0350bc7/src/BaselineOfMaterialDesignLite.package/BaselineOfMaterialDesignLite.class/instance/projectClass.st) just because they a) want to take advantage of a recent feature/bugfix in Metacello and b) want to ensure that their project runs cleanly on a given platform that may not come with the needed feature installed by default ...

**Comment by dalehenrich** [comment]
BTW, with this option it would be possible to run tests against vanilla images (and expect failures) as well as run again images with the latest Metacello version installed (and expect success) ...

**Comment by noha** [comment]
I'm totally fine with it if it is an option;)
