### ISSUE TITLE
ToDo in VOMongoRepository>>select*

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#70]
"Selecting instances of aClass should be done in the mongo query"

I only copy what's in the code:

```
basicSelectMany: aClass where: aDictionary limit: limit offset: offset
    "Selecting instances of aClass should be done in the mongo query, not here"
    self flag: #todo.

    ^((self basicRawSelectMany:  aClass where: aDictionary limit: limit offset: offset)
        collect: [ :each | self retrieveObjectOf: aClass json: each ]
        as: repository collectionClass)
            select: [ :each | each isKindOf: aClass ]
```

I didn't understand why was the select there, but found that `testSaveWithSubclasses` shows why it's necessary.

**Comment by tinchodias** [comment]
What to you think of this fix? it works but I don't know where to place it... 

```
basicSelectMany: aClass where: aDictionary limit: limit offset: offset

	aDictionary 
		at: '#instanceOf' 
		put: (Dictionary with: '$in' -> (aClass withAllSubclasses collect: #asString)).
	
	^(self basicRawSelectMany: aClass where: aDictionary limit: limit offset: offset)
		collect: [ :each | self retrieveObjectOf: aClass json: each ]
		as: repository collectionClass
```
The comment suggests that MongoQuery should know about classes and then add the query to the dictionary? Maybe it's fine if Voyage does it (of course, reusing code, I don't mean to copy&paste in the 3 basicSelect*)

**Comment by noha** [comment]
Moving the filter from the image side to the database side is a good idea. Regarding the limit the in-image filter is plain wrong. The problem with your change is that is not performant for the default case. Meaning the most common use case is where the root class of a collection is used for querying. In this default case where there is a decent subclass hierarchy it would slow down querying. The point here is that if the class of the query is the root class of the collection we don't need to filter. So the most common use case would be even faster than before

You should change the code to this
`
aClass = aClass persistentClass ifFalse: [
  aDictionary 
          at: '#instanceOf' 
          put: (Dictionary with: '$in' -> (aClass withAllSubclasses collect: #asString)).
]`

This would be an improvement of the current situation because it is faster for the common use case and there is no select: which spares addtional cycles if the requested collection is big.
But there is also a remaining problem. #withAllSubclasses is not the right approach. I'm not sure there is a real problem but if a subclass of a voyageRoot implement #isVoyageRoot itself those objects will located in a different collection. So we need to figure out all subclasses that do not implement #isVoyageRoot. To be very exact it would be every subclass that does not implement #isVoyageRoot or that does implement it but has the same #voyageCollectionName like the base class.
What do you think?

**Comment by tinchodias** [comment]
Ah, I find #persistentClass strange. Why it matters only if it implements #isVoyageRoot and not the boolean answer?
```
Class>>
persistentClass
	self == Object ifTrue: [ ^ nil ]. 
	(self class selectors includes: #isVoyageRoot)
		ifTrue: [ ^self ] 
		ifFalse: [ ^self superclass persistentClass ]
```

**Comment by tinchodias** [comment]
+1 I see your point and agree it's important to optimize the most common case (but still don't understand implementation details)

**Comment by tinchodias** [comment]
1) it's offtopic, and 2) we should benchmarks it... but it smells #persistentClass and #voyageCollectionName could be cached. Maybe in the VOMongoRepository's cache.
```
Class>>
voyageCollectionName
	"This method can be overridden with a more meaningful collection name"
	self isVoyageRoot ifFalse: [ ^ self name asString ].
	^ ((self persistentClass name first: 3) allSatisfy: #isUppercase)
		ifTrue: [ (self persistentClass name allButFirst: 2) ] 
		ifFalse: [ self persistentClass name ]
```

**Comment by noha** [comment]
Good point about the return value of #isVoyageRoot. We need to change that. Always depends on the use case we want to support. I'm not totally clear what could be the reason for a class hierarchie that is voyage root where a sub hierarchie returns voyageRoot false

**Comment by noha** [comment]
About voyageCollectionName and persistentClass I do not think there is potential for optimization. Managing the names would probably be more expensive then generating the value. And caches are always dangerous to use.

**Comment by tinchodias** [comment]
Yes... benchmarks are needed to decide optimizations. If it's the case, I think this could work: flush the cache of voyageCollectionName or persistentClass when any code change is announced in the SystemAnnouncer.

**Comment by noha** [comment]
Can we close this?

**Comment by noha** [comment]
This will take a while to fix. For the mongo and dictionary case it is easy to do. For extending a query it is a bit more to do. First I need proper integration of PersistenceQuery

**Comment by tinchodias** [comment]
> Can we close this?

We can close it

**Comment by noha** [comment]
Ok, I repoen that later
